const mockMarketSnapshots = {
  SPCX: {
    symbol: "SPCX",
    name: "SpaceX Intelligence",
    price: 165.32,
    change: 12.09,
    changePercent: 7.89,
    lastUpdate: "2 min ago",
    currency: "USD",
  },
  TSLA: {
    symbol: "TSLA",
    name: "Tesla",
    price: 323.63,
    change: 4.72,
    changePercent: 1.48,
    lastUpdate: "2 min ago",
    currency: "USD",
  },
  NVDA: {
    symbol: "NVDA",
    name: "NVIDIA",
    price: 157.54,
    change: 2.31,
    changePercent: 1.49,
    lastUpdate: "2 min ago",
    currency: "USD",
  },
  AAPL: {
    symbol: "AAPL",
    name: "Apple",
    price: 201.08,
    change: -1.16,
    changePercent: -0.57,
    lastUpdate: "2 min ago",
    currency: "USD",
  },
  THYAO: {
    symbol: "THYAO",
    name: "Türk Hava Yolları",
    price: 267.5,
    change: 3.25,
    changePercent: 1.23,
    lastUpdate: "3 dk önce",
    currency: "TRY",
  },
  ASELS: {
    symbol: "ASELS",
    name: "Aselsan",
    price: 156.8,
    change: 1.9,
    changePercent: 1.23,
    lastUpdate: "3 dk önce",
    currency: "TRY",
  },
  TUPRS: {
    symbol: "TUPRS",
    name: "Tüpraş",
    price: 142.4,
    change: -0.85,
    changePercent: -0.59,
    lastUpdate: "3 dk önce",
    currency: "TRY",
  },
  KCHOL: {
    symbol: "KCHOL",
    name: "Koç Holding",
    price: 166.1,
    change: 2.1,
    changePercent: 1.28,
    lastUpdate: "3 dk önce",
    currency: "TRY",
  },
  BTC: {
    symbol: "BTC",
    name: "Bitcoin",
    price: 106842.17,
    change: 1284.32,
    changePercent: 1.22,
    lastUpdate: "1 dk önce",
    currency: "USD",
  },
  ETH: {
    symbol: "ETH",
    name: "Ethereum",
    price: 2448.61,
    change: 38.45,
    changePercent: 1.6,
    lastUpdate: "1 dk önce",
    currency: "USD",
  },
  SOL: {
    symbol: "SOL",
    name: "Solana",
    price: 148.27,
    change: -2.14,
    changePercent: -1.42,
    lastUpdate: "1 dk önce",
    currency: "USD",
  },
  XRP: {
    symbol: "XRP",
    name: "XRP",
    price: 2.18,
    change: 0.06,
    changePercent: 2.83,
    lastUpdate: "1 dk önce",
    currency: "USD",
  },
};

export function getMarketSnapshot(symbol) {
  const normalizedSymbol = symbol?.trim().toUpperCase();
  const snapshot = mockMarketSnapshots[normalizedSymbol];

  return snapshot ? { ...snapshot } : null;
}
